### ISSUE TITLE
CLAs require signatures

### ISSUE THREAD

**Issue by cookiengineer** [clabot/clabot#17]
Hey guys,

I talked to my lawyer about CLAs for our project - if they are necessary, why and when we need them, etc. pp. He told me that CLAs overall are only valid with a signature - at least in Germany, Swiss, France and the major EU countries he is familar with due to clients in the past.

Is there an option available to have a signature field, like using HTML5 canvas for mobile phones or attaching a signature image file?

**Comment by toddw** [comment]
Can you ask your lawyer if a digital signature like signed on HTML 5 canvas would be acceptable?

**Comment by cookiengineer** [comment]
Yes, it would be acceptable if the signature is on the same document.

Most companies use the digital signature service of Adobe (formerly EchoSign): https://acrobat.adobe.com/us/en/sign.html

The main reason people use that service is that you can sign a PDF with that service using your Touchpad or mobile device (using your fingers and canvas for the signature field).

Another reason is that the PDFs are digitally signed afterwards (by Adobe) - but that is optional as the signed documents themselves are also legally valid. The digital signature part is just in case somebody denies having signed the PDF in the first place in front of the court.

**Comment by cookiengineer** [comment]
@toddw Is this project still maintained?

Otherwise I'd close this issue due to inactivity. Just reopen it if clabot is still an active project.

**Comment by toddw** [comment]
I'm volunteering, but I do not have access to reopen the issue

**Comment by cookiengineer** [comment]
I have no idea about the clabot codebase, so I guess I can't help much. I'm also not so good in coffeescript, but I would love to help in other things like testing etc.

**Comment by lieutdan13** [comment]
This repository is no longer maintained. Archiving the repository.
